version: '3'

services:

  jenkins:
    image: jenkins:2.121.3
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - /jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
